### ISSUE TITLE
Transition to `Publish-PasswordHealth` from `Publish-LocalUserExpiry`

### ISSUE THREAD

**Issue by bhumitra** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#90] opened 2023-02-09 18:45 UTC
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

- `Publish-PasswordHealth` reads data from SOS Utility and adds it to the html report. Before VCF 4.4, it didnt include local user account. 
- `Publish-LocalUserExpiry` connects to individual components in SDDC and collects the data from there including local user account. 

As of 4.4, both cmdlets return the same data.

### Use Case(s)

This enhancement will help:
- Add the password expiry to the report.
- Increases the speed of the report.

### Potential Configuration

NA

**Comment by tenthirtyam** [comment] 2023-02-24 19:02
Duplicate of #40

**Comment by tenthirtyam** [comment] 2023-02-24 19:03
Closing this issue in favor of #40. Context from this issue has been copied to the preceding issue.

**Comment by tenthirtyam** [comment] 2023-03-07 19:10
Reopening this issue.

Taking a look at the information returned:

**`Publish-PasswordHealth`**

```pwsh
Component Resource                        Alert Message
--------- --------                        ----- -------
ESXI      sfo01-m01-esx01.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-m01-esx01.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-m01-esx02.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-m01-esx02.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-m01-esx03.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-m01-esx03.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-m01-esx04.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-m01-esx04.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-w01-esx01.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-w01-esx01.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-w01-esx02.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-w01-esx02.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-w01-esx03.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-w01-esx03.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-w01-esx04.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
ESXI      sfo01-w01-esx04.sfo.rainpole.io GREEN ESXI password is set to never expired. Verified using command Check password expiry with PyVim
NSX       sfo-m01-en01.sfo.rainpole.io    GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-m01-en01.sfo.rainpole.io    GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-m01-en01.sfo.rainpole.io    GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-m01-en02.sfo.rainpole.io    GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-m01-en02.sfo.rainpole.io    GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-m01-en02.sfo.rainpole.io    GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-m01-nsx01.sfo.rainpole.io   GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-m01-nsx01.sfo.rainpole.io   GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-m01-nsx01.sfo.rainpole.io   GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-w01-en01.sfo.rainpole.io    GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-w01-en01.sfo.rainpole.io    GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-w01-en01.sfo.rainpole.io    GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-w01-en02.sfo.rainpole.io    GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-w01-en02.sfo.rainpole.io    GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-w01-en02.sfo.rainpole.io    GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-w01-nsx01.sfo.rainpole.io   GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
NSX       sfo-w01-nsx01.sfo.rainpole.io   GREEN NSX password expiration date is far enough. Verified using Check password expiry with v1/node/users API
SDDC      sfo-vcf01.sfo.rainpole.io       GREEN SDDC password expiration date is far enough. Verified using shell chage -l root
SDDC      sfo-vcf01.sfo.rainpole.io       GREEN SDDC password expiration date is far enough. Verified using shell chage -l vcf
SDDC      sfo-vcf01.sfo.rainpole.io       GREEN SDDC password expiration date is far enough. Verified using shell chage -l backup
vCenter   sfo-m01-vc01.sfo.rainpole.io    GREEN vCenter password expiration date is far enough. Verified using Check password expiry with api/appliance/local-accounts API
vCenter   sfo-w01-vc01.sfo.rainpole.io    GREEN vCenter password expiration date is far enough. Verified using Check password expiry with api/appliance/local-accounts API
```

**`Publish-LocalUserExpiry`**

```pwsh
Component	Resource	User	Alert	Message
NSX Edge	sfo-m01-en01.sfo.rainpole.io	root	GREEN	Password will not expire within the next 15 days. Verified using chage -l root.
NSX Edge	sfo-m01-en01.sfo.rainpole.io	audit	GREEN	Password will not expire within the next 15 days. Verified using chage -l audit.
NSX Edge	sfo-m01-en01.sfo.rainpole.io	admin	GREEN	Password will not expire within the next 15 days. Verified using chage -l admin.
NSX Edge	sfo-m01-en02.sfo.rainpole.io	root	GREEN	Password will not expire within the next 15 days. Verified using chage -l root.
NSX Edge	sfo-m01-en02.sfo.rainpole.io	audit	GREEN	Password will not expire within the next 15 days. Verified using chage -l audit.
NSX Edge	sfo-m01-en02.sfo.rainpole.io	admin	GREEN	Password will not expire within the next 15 days. Verified using chage -l admin.
NSX Manager	sfo-m01-nsx01a.sfo.rainpole.io	root	GREEN	Password will not expire within the next 15 days. Verified using chage -l root.
NSX Manager	sfo-m01-nsx01a.sfo.rainpole.io	admin	GREEN	Password will not expire within the next 15 days. Verified using chage -l admin.
NSX Manager	sfo-m01-nsx01a.sfo.rainpole.io	audit	GREEN	Password will not expire within the next 15 days. Verified using chage -l audit.
vCenter	sfo-m01-vc01.sfo.rainpole.io	root	GREEN	Password will not expire within the next 15 days. Verified using chage -l root.
SDDC	sfo-vcf01.sfo.rainpole.io	vcf	GREEN	Password will not expire within the next 15 days. Verified using chage -l vcf.
SDDC	sfo-vcf01.sfo.rainpole.io	backup	GREEN	Password will not expire within the next 15 days. Verified using chage -l backup.
SDDC	sfo-vcf01.sfo.rainpole.io	root	GREEN	Password will not expire within the next 15 days. Verified using chage -l root.
NSX Edge	sfo-w01-en01.sfo.rainpole.io	root	GREEN	Password will not expire within the next 15 days. Verified using chage -l root.
NSX Edge	sfo-w01-en01.sfo.rainpole.io	admin	GREEN	Password will not expire within the next 15 days. Verified using chage -l admin.
NSX Edge	sfo-w01-en01.sfo.rainpole.io	audit	GREEN	Password will not expire within the next 15 days. Verified using chage -l audit.
NSX Edge	sfo-w01-en02.sfo.rainpole.io	admin	GREEN	Password will not expire within the next 15 days. Verified using chage -l admin.
NSX Edge	sfo-w01-en02.sfo.rainpole.io	audit	GREEN	Password will not expire within the next 15 days. Verified using chage -l audit.
NSX Edge	sfo-w01-en02.sfo.rainpole.io	root	GREEN	Password will not expire within the next 15 days. Verified using chage -l root.
NSX Manager	sfo-w01-nsx01a.sfo.rainpole.io	root	GREEN	Password will not expire within the next 15 days. Verified using chage -l root.
NSX Manager	sfo-w01-nsx01a.sfo.rainpole.io	audit	GREEN	Password will not expire within the next 15 days. Verified using chage -l audit.
NSX Manager	sfo-w01-nsx01a.sfo.rainpole.io	admin	GREEN	Password will not expire within the next 15 days. Verified using chage -l admin.
vCenter	sfo-w01-vc01.sfo.rainpole.io	root	GREEN	Password will not expire within the next 15 days. Verified using chage -l root.
```

The `Publish-PasswordHealth` cmdlet is more complete as it also covers ESXi; however, it would need to be modified to show the user account. Which would require a rewrite not to use the generic `Read-JsonElement` cmdlet in the module.

**Closed** 2023-04-04 11:35 UTC
Labels: enhancement, vcf/4.4+
