### ISSUE TITLE
`Request-VcenterBackupStatus` returns incorrect results

### ISSUE THREAD

**Issue by robbuxton** [vmware/powershell-module-for-vmware-cloud-foundation-reporting#153] opened 2023-06-29 21:04 UTC
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/powershell-module-for-cloud-foundation-reporting/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

4.5.1

### PowerShell Version

Linux 7.3.4

### PowerCLI Version

13.1.0.21624340

### Module Version

2.2.0.1000

### PowerValidatedSolutions Version

2.4.0.1008

### PowerVCF Version

2.3.0.1004

### Guest Operating System

VMware Photon 5.0

### Environment Details

The environment is a new VCF deployment using VCF 4.5.1
vCenter version: 7.0.3, Aria Operations 8.12.0
VCF has 2 x SDDC, 2 x Domains per SDDC.
Account being used for SDDC Connection has Admin rights
Backups have been configured for all vCenter Servers - 4 in total.
And apologies, very new to GitHub, so if I've missed something or data incorrect 

### Description

When running the VCF HRM solution the data returned in the json file for vCenter Backups shows:
"Date": null
"Alert": "RED"
"Message": "Backup is not configured."
All other backups are correctly reporting.

### Error or Debug Output

![Issue Test-3](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-reporting/assets/138164283/053070dc-01d0-45c2-a1e4-264fec911a55)

![Issue Test-1](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-reporting/assets/138164283/f4112367-9384-47b4-b238-8fd6e5e562f6)

### Expected Behavior

Expected that the returned output would show Backups Green and running as per active configuration.

### Actual Behavior

Dashboards show Red, returned json file lists backups as not configured, not running

### Steps to Reproduce

Run Request-VcenterBackupStatus after getting token and providing credentials for SDDC Manager reproduces the result. As does running the HRM Send-data-to-vrops.py jobs.

**Comment by tenthirtyam** [comment] 2023-06-29 21:08
Tagged for the v2.3.0 milestone. Assigning to @bhumitra.

**Comment by tenthirtyam** [comment] 2023-07-13 21:50
I've reproduced the issue and have tracked down the issue.

This false-negative only manifests on PowerShell 7 on Linux.

**Windows PowerShell** (5.1):

```powershell
PS C:\Users\Administrator> Request-VcenterBackupStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1
!VMw@re1! -domain sfo-m01

Component : vCenter Server
Resource  : vCenter Server Backup Operation
Element   : sfo-m01-vc01.sfo.rainpole.io
Domain    : sfo-m01
Date      : 7/13/2023 1:01:04 AM
Alert     : GREEN
Message   : The backup completed without errors. Backup is less than 1 day old.
```

**PowerShell 7 on Windows**:

```powershell
PS C:\Users\Administrator> Request-VcenterBackupStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -domain sfo-m01

Component : vCenter Server
Resource  : vCenter Server Backup Operation
Element   : sfo-m01-vc01.sfo.rainpole.io
Domain    : sfo-m01
Date      : 7/13/2023 12:01:04 AM
Alert     : GREEN
Message   : The backup completed without errors. Backup is less than 1 day old.
```

**PowerShell 7 on PhotonOS**:

```powershell
PS /home/vmware> Request-VcenterBackupStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -domain sfo-m01

Component : vCenter Server
Resource  : vCenter Server Backup Operation
Element   : sfo-m01-vc01.sfo.rainpole.io
Domain    : sfo-m01
Date      :
Alert     : RED
Message   : Backup is not configured.
```

However, the issue is not within this module, it's in the `PowerValidatedSolutions` module in the `Request-VcenterApiToken` which needs to pass the `-skipCertificateCheck` option if `Core` and `Linux`.

**Example**:

```powershell
Try {
    $uri = "https://$vcenterApiServer/api/session" # Perform the vCenter REST API call to authenticate and retrieve the session token
    if ($PSEdition -eq "Core" -and ($PSVersionTable.OS).Split(' ')[0] -eq "Linux") {
        $response = Invoke-WebRequest -Method 'POST' -Uri $uri -Headers $vcenterAuthHeaders -UseBasicParsing -SkipCertificateCheck
    } else {
        $response = Invoke-WebRequest -Method 'POST' -Uri $uri -Headers $vcenterAuthHeaders -UseBasicParsing
    }
```

I'll open a pull request on `PowerValidatedSolutions` to address this issue and target the v2.5.0 milestone.

Ryan

**Comment by tenthirtyam** [comment] 2023-07-13 22:33
Dependency fix: https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/pull/292

**Comment by tenthirtyam** [comment] 2023-07-14 14:48
Merged: https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/pull/292

**Closed** 2023-07-17 23:22 UTC
Labels: bug
